server:
  port: 7001
  servlet:
    context-path: /eureka-client-shop-product

spring:
  application:
    name: eureka-client-shop-product
  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver # JDBC连接Mysql6以上com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    #    url: jdbc:mysql://10.211.55.3:3306/elasticsearchshop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    url: jdbc:p6spy:mysql://10.211.55.3:3306/elasticsearchshop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: zsyubo
    password: 123456

eureka:
  client:
    service-url:
      #      defaultZone: http://server1:8000/eureka/,http://server2:8001/eureka/,http://server3:8002/eureka/
      defaultZone: http://server1:8000/eureka/

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples: debug

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: test-group
