server:
  port: 7001
  servlet:
    context-path: /eureka-client-shop-product

spring:
  application:
    name: eureka-client-shop-product

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/,http://server2:8001/eureka/,http://server3:8002/eureka/
#      defaultZone: http://server1:8000/eureka/

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
